package com.ubs.emp.engagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppSubjectTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSubjectTypeAllPropertiesEquals(AppSubjectType expected, AppSubjectType actual) {
        assertAppSubjectTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertAppSubjectTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSubjectTypeAllUpdatablePropertiesEquals(AppSubjectType expected, AppSubjectType actual) {
        assertAppSubjectTypeUpdatableFieldsEquals(expected, actual);
        assertAppSubjectTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSubjectTypeAutoGeneratedPropertiesEquals(AppSubjectType expected, AppSubjectType actual) {
        assertThat(expected)
            .as("Verify AppSubjectType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSubjectTypeUpdatableFieldsEquals(AppSubjectType expected, AppSubjectType actual) {
        assertThat(expected)
            .as("Verify AppSubjectType relevant properties")
            .satisfies(e -> assertThat(e.getSubjectCode()).as("check subjectCode").isEqualTo(actual.getSubjectCode()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSubjectTypeUpdatableRelationshipsEquals(AppSubjectType expected, AppSubjectType actual) {}
}
