package com.ubs.emp.engagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppSubjectConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSubjectConfigAllPropertiesEquals(AppSubjectConfig expected, AppSubjectConfig actual) {
        assertAppSubjectConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertAppSubjectConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSubjectConfigAllUpdatablePropertiesEquals(AppSubjectConfig expected, AppSubjectConfig actual) {
        assertAppSubjectConfigUpdatableFieldsEquals(expected, actual);
        assertAppSubjectConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSubjectConfigAutoGeneratedPropertiesEquals(AppSubjectConfig expected, AppSubjectConfig actual) {
        assertThat(expected)
            .as("Verify AppSubjectConfig auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSubjectConfigUpdatableFieldsEquals(AppSubjectConfig expected, AppSubjectConfig actual) {
        assertThat(expected)
            .as("Verify AppSubjectConfig relevant properties")
            .satisfies(e -> assertThat(e.getSubjectCode()).as("check subjectCode").isEqualTo(actual.getSubjectCode()))
            .satisfies(e -> assertThat(e.getVersion()).as("check version").isEqualTo(actual.getVersion()))
            .satisfies(e -> assertThat(e.getPayload()).as("check payload").isEqualTo(actual.getPayload()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSubjectConfigUpdatableRelationshipsEquals(AppSubjectConfig expected, AppSubjectConfig actual) {}
}
