package com.ubs.emp.engagement.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppTopicLookupAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppTopicLookupAllPropertiesEquals(AppTopicLookup expected, AppTopicLookup actual) {
        assertAppTopicLookupAutoGeneratedPropertiesEquals(expected, actual);
        assertAppTopicLookupAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppTopicLookupAllUpdatablePropertiesEquals(AppTopicLookup expected, AppTopicLookup actual) {
        assertAppTopicLookupUpdatableFieldsEquals(expected, actual);
        assertAppTopicLookupUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppTopicLookupAutoGeneratedPropertiesEquals(AppTopicLookup expected, AppTopicLookup actual) {
        assertThat(expected)
            .as("Verify AppTopicLookup auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppTopicLookupUpdatableFieldsEquals(AppTopicLookup expected, AppTopicLookup actual) {
        assertThat(expected)
            .as("Verify AppTopicLookup relevant properties")
            .satisfies(e -> assertThat(e.getTopicCode()).as("check topicCode").isEqualTo(actual.getTopicCode()))
            .satisfies(e -> assertThat(e.getTopicName()).as("check topicName").isEqualTo(actual.getTopicName()))
            .satisfies(e -> assertThat(e.getTargetGroup()).as("check targetGroup").isEqualTo(actual.getTargetGroup()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppTopicLookupUpdatableRelationshipsEquals(AppTopicLookup expected, AppTopicLookup actual) {}
}
